name: Deploy Quarto Site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout your repository to the GitHub runner

    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2  # Install Quarto

    - name: Install dependencies
      run: |
        sudo apt-get install -y libcurl4-openssl-dev  # Install any required dependencies for Quarto

    - name: Render Quarto site
      run: |
        quarto render  # Build the Quarto site

    - name: Deploy to GitHub Pages
      run: |
        quarto publish gh-pages  # Publish the rendered site to the gh-pages branch
